server:
  port: 8082

spring:
  application:
    name: jobms


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobmsDB?serverTimezone=UTC
    name: jobmsDB

    password: **************
    username: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      #hibernate:
      format_sql: true